# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package
env:
# Precisa das varviaveis de org id e project id
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
     
    steps:
      
      - uses: actions/checkout@v3
        with:
            node-version: 20
      - name: Babel install
        working-directory: ./api_teste_cors
        run: npm install -g babel-cli
      - name: Run build
        working-directory: ./api_teste_cors
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            node-version: 20
      - name: Vercel Install
        run: npm install vercel -g
         
      - name: Vercel deploy
        run: vercel --cwd ./public --token ${{ env.VERCEL_TOKEN }} --prod
     
